import { useState } from "react";
import {
  Loader,
  Send,
  Sparkles,
  Image as ImageIcon,
  Wand2,
} from "lucide-react";

const ImageGenerator = () => {
  const [input, setInput] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [result, setResult] = useState(null);
  const handleGenerate = async () => {
    if (!input.trim()) return;
    setIsLoading(true);
    setResult(null);

    try {
      const response = await fetch("http://localhost:5001/api/generate-image", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt: input }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || "Failed to generate image");
      }

      setResult(data);
    } catch (error) {
      console.error("Error generating image:", error);
      alert("Lỗi khi tạo ảnh: " + error.message);
    } finally {
      setIsLoading(false);
    }
  };

  const handleKeyDown = (e) => {
    if (e.key === "Enter" && !isLoading) {
      handleGenerate();
    }
  };

  return (
    <div className="flex flex-col items-center w-full max-w-3xl mx-auto p-4 gap-6">
      <div className="text-center space-y-2">
        <h2 className="text-3xl font-bold flex items-center justify-center gap-2">
          <Sparkles className="text-primary w-8 h-8" />
          AI Image Generator
        </h2>
        <p className="text-base-content/60">
          Nhập ý tưởng của bạn, Gemini sẽ viết prompt và Stable Diffusion sẽ vẽ
          nó.
        </p>
      </div>

      <div className="w-full relative">
        <div className="join w-full shadow-sm">
          <input
            type="text"
            className="input input-bordered join-item w-full focus:outline-none"
            placeholder="Ví dụ: Một phi hành gia cưỡi ngựa trên sao Hỏa..."
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={handleKeyDown}
            disabled={isLoading}
          />
          <button
            className="btn btn-primary join-item min-w-[120px]"
            onClick={handleGenerate}
            disabled={isLoading || !input.trim()}
          >
            {isLoading ? (
              <>
                <Loader className="w-5 h-5 animate-spin" />
                Processing...
              </>
            ) : (
              <>
                <Wand2 className="w-5 h-5" />
                Generate
              </>
            )}
          </button>
        </div>
      </div>

      <div className="w-full">
        {isLoading && !result && (
          <div className="flex flex-col gap-4 w-full animate-pulse">
            <div className="h-64 bg-base-300 rounded-xl w-full"></div>
            <div className="h-4 bg-base-300 rounded w-3/4"></div>
            <div className="h-4 bg-base-300 rounded w-1/2"></div>
          </div>
        )}

        {result && (
          <div className="card bg-base-100 shadow-xl border border-base-200 overflow-hidden animate-in fade-in zoom-in duration-500">
            <figure className="relative bg-black/5">
              <img
                src={result.imageUrl}
                alt="Generated Art"
                className="w-full h-auto object-contain max-h-[600px]"
              />
              <div className="absolute top-2 right-2 badge badge-secondary">
                Generated by AI
              </div>
            </figure>

            <div className="card-body gap-4">
              <div>
                <h3 className="text-sm font-bold text-base-content/70 uppercase tracking-wider mb-1 flex items-center gap-2">
                  <ImageIcon className="w-4 h-4" /> Original Input
                </h3>
                <p className="text-lg font-medium">{result.originalPrompt}</p>
              </div>

              <div className="bg-base-200 p-4 rounded-lg border border-base-300">
                <h3 className="text-xs font-bold text-primary uppercase tracking-wider mb-2 flex items-center gap-2">
                  <Sparkles className="w-3 h-3" /> Enhanced by Gemini
                </h3>
                <p className="text-sm italic text-base-content/80 font-mono">
                  "{result.refinedPrompt}"
                </p>
              </div>

              <div className="card-actions justify-end mt-2">
                <a
                  href={result.imageUrl}
                  download="ai-generated-image.jpg"
                  className="btn btn-outline btn-sm"
                >
                  Download Image
                </a>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default ImageGenerator;
